language: cpp

sudo: enabled

compiler:
    - g++

os:
    - linux

addons:
    apt:
        update: true
        packages:
        - libpcap-dev
        - libssl-dev

before_script:
    - ./setup.sh
    - cd source/tests
    - make check
    - cd ../..

script:
    - sudo ~/misterbianco/build/test
