language: cpp

sudo: enabled

compiler:
    - g++

os:
    - linux

addons:
    apt:
        packages:
        - libpcap-dev
        - libssl-dev

before_script:
    - ./setup.sh
    - cd source/tests
    - make check
    - sudo ldconfig

scripts:
    - sudo ./build/test
